# Generated by Django 2.1.1 on 2018-10-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindful', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
